arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: l10n.dart
output-class: S
output-dir: lib/l10n/generated
synthetic-package: false
nullable-getter: false
format: true
use-deferred-loading: false
header: '// ignore_for_file: non_constant_identifier_names, use_super_parameters, unnecessary_string_escapes'
